"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

export default function ReportsPage() {
  const router = useRouter();
  const [metrics, setMetrics] = useState({ patients: "—", visits: "—", payments: "—" });
  useEffect(() => { async function load() { if (!supabase) return; const { data: session } = await supabase.auth.getSession(); if (!session.session) { router.replace("/login"); return; } const { data: profile } = await supabase.from("profiles").select("role").eq("id", session.session.user.id).maybeSingle(); if (profile?.role !== "doctor") { router.replace("/pharmacy"); return; } const [patients, visits, payments] = await Promise.all([supabase.from("patients").select("id", { count: "exact", head: true }), supabase.from("visits").select("id", { count: "exact", head: true }), supabase.from("payments").select("amount")]); const total = (payments.data || []).reduce((sum, payment) => sum + Number(payment.amount || 0), 0); setMetrics({ patients: String(patients.count ?? 0), visits: String(visits.count ?? 0), payments: `₹${total.toLocaleString("en-IN")}` }); } load(); }, [router]);
  return <main className="reports-shell"><header className="topbar"><div className="mobile-brand"><span className="mobile-mark">S</span><strong>Sugam Homeo</strong></div><div className="breadcrumb"><span>Manage</span><b>/</b><strong>Reports</strong></div><div className="top-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => document.documentElement.classList.toggle("dark")}>☾</button><div className="top-avatar">DS</div></div></header><div className="page-content"><button className="back-link" onClick={() => router.push("/")}>← Back to overview</button><div className="welcome-row"><div><p className="eyebrow">Practice insights</p><h1>Reports</h1><p className="subheading">A simple view of your clinic&apos;s recorded activity.</p></div></div><div className="stats-grid"><Stat label="Total patients" value={metrics.patients} tone="blue" /><Stat label="Total visits" value={metrics.visits} tone="maroon" /><Stat label="Payments recorded" value={metrics.payments} tone="green" /><Stat label="Clinic location" value="Salem" tone="gold" /></div><section className="panel report-note"><div className="panel-heading"><div><h2>Reporting foundation</h2><p>These numbers are read from the shared Supabase records and will grow with the visit history.</p></div></div><div className="report-note-body"><span>Next reporting layer</span><strong>Revenue by period, visit trends, pharmacy turnaround, and outstanding balances.</strong><p>No clinical decision-making is automated by Sugam Homeo.</p></div></section></div></main>;
}
function Stat({ label, value, tone }: { label: string; value: string; tone: string }) { return <article className="stat-card"><div className={`stat-icon ${tone}`}>◫</div><div><p>{label}</p><strong>{value}</strong><span>From live clinic records</span></div></article>; }
