"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type Payment = { id: string; patient: string; patientId: string; visit: string; amount: number; method: string; receivedAt: string };

export default function PaymentsPage() {
  const router = useRouter();
  const [payments, setPayments] = useState<Payment[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { async function load() { if (!supabase) return; const { data: session } = await supabase.auth.getSession(); if (!session.session) { router.replace("/login"); return; } const { data } = await supabase.from("payments").select("id,amount,payment_method,received_at,visits!inner(visit_number,patients!inner(name,patient_number))").order("received_at", { ascending: false }).limit(100); setPayments((data || []).map((item: any) => ({ id: item.id, patient: item.visits.patients.name, patientId: item.visits.patients.patient_number, visit: `Visit #${item.visits.visit_number}`, amount: Number(item.amount), method: item.payment_method || "Not specified", receivedAt: new Date(item.received_at).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) }))); setLoading(false); } load(); }, [router]);
  const total = payments.reduce((sum, payment) => sum + payment.amount, 0);
  return <main className="reports-shell"><header className="topbar"><div className="mobile-brand"><span className="mobile-mark">S</span><strong>Sugam Homeo</strong></div><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>Payments</strong></div><div className="top-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => document.documentElement.classList.toggle("dark")}>☾</button><div className="top-avatar">DS</div></div></header><div className="page-content"><button className="back-link" onClick={() => router.push("/")}>← Back to overview</button><div className="welcome-row"><div><p className="eyebrow">Transaction history</p><h1>Payments</h1><p className="subheading">Every payment remains attached to the visit that received it.</p></div></div><div className="stats-grid"><Stat label="Recorded payments" value={String(payments.length)} tone="blue" /><Stat label="Total received" value={`₹${total.toLocaleString("en-IN")}`} tone="green" /><Stat label="Payment model" value="Transactions" tone="gold" /><Stat label="Source" value="Supabase" tone="maroon" /></div><section className="panel payments-panel"><div className="panel-heading"><div><h2>Recent payments</h2><p>Newest transactions first</p></div></div>{loading ? <div className="empty-state">Loading transactions…</div> : <div className="payment-table"><div className="payment-head"><span>Patient</span><span>Visit</span><span>Method</span><span>Received</span><span>Amount</span></div>{payments.map((payment) => <div className="payment-row" key={payment.id}><div><strong>{payment.patient}</strong><span>{payment.patientId}</span></div><span>{payment.visit}</span><span className="payment-method">{payment.method}</span><span className="payment-date">{payment.receivedAt}</span><strong>₹{payment.amount.toLocaleString("en-IN")}</strong></div>)}{!payments.length && <div className="empty-state">No payments recorded yet.</div>}</div>}</section></div></main>;
}
function Stat({ label, value, tone }: { label: string; value: string; tone: string }) { return <article className="stat-card"><div className={`stat-icon ${tone}`}>₹</div><div><p>{label}</p><strong>{value}</strong><span>From live clinic records</span></div></article>; }
